favicon: null
name: globalcitizentraces
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.3533332969527692
  brandStrength: 0.1241611130535603
  rhythmicContrast: 0.7932712726760656
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  lightness: 0.7558214152231812
typography_spectrum: 0.4986759540624917
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.966792
analytics:
  twitter: null
  google: null
  facebook: null
