name: globalcitizentraces
favicon: null
layout_spectrum: 0.74173
typography_spectrum: 0.4986759540624917
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1241611130535603
  lightness: 0.7558214152231812
  saturation: 0.3533332969527692
  rhythmicContrast: 0.7932712726760656
purpose: []
